### PR TITLE
[WIP] Add Travis

### PR DESCRIPTION
**Pull request by cgewecke**
#1 Enables codechecks for Travis.

@krzkaczor Not sure this is correct.. am currently blocked in [my Travis testing](https://github.com/cgewecke/gas-check/pull/21) by an error that appears when running a push build:
```
$ npx codechecks
Running codechecks!
Executing 1 codechecks files
{ [Error: no reference found for shorthand 'master'] errno: -3, errorFunction: 'Reference.dwim' }
```

Looks like it comes from node-git - relevant issue about it [here](https://github.com/nodegit/nodegit/issues/1497). 

+ Do I have to specify a speculative branch?
+ Is Circle turned on for the monorepo? :)

### CODE REVIEW

**Comment by krzkaczor** [comment]
Hey! Thank you so much for working on this. It's quite late in here so I will do a proper review tomorrow but here's a quick response.

I think I know exactly this problem. It was hard to find `master` (base) branch commit on CircleCI as well. The root of the problem is that git repository cloned by CI providers is in some "weird" state. 

For example, on CirceCI it was checkout on a feature branch but the local master branch was already merged with it so `SHA(FeatureBranch) === SHA(master)`... That's why I needed to fetch remote branches and check HEAD of origin/master: https://github.com/codechecks/monorepo/blob/master/packages/client/src/speculativeBranchSelection.ts#L53 I guess something very similar happens on travis. Can you connect via SSH to failed build to debug it? (its possible on CircleCI) I would suggest printing out `git branch -a` and basically figuring out a way to get SHA of HEAD of a different branch. If it's again CI specific probably this logic should be moved to CI provider. I can definitely help you tmrw figuring that out.

Another note would be that according to build description: https://stackoverflow.com/questions/41524861/travis-failed-push-but-passed-pr we should build a simple mechanism that would skip build entirely for a PR travis build. Since we don't want to execute codechecks twice.

> Is Circle turned on for the monorepo? :)

Thanks, FIXED! It was turn off for forks.

**Comment by cgewecke** [comment]
Some notes about the default git behavior in Travis  for further investigation....

Example checkout  for **Pull Requests**
```
$ git clone --depth=50 https://github.com/cgewecke/gas-check.git cgewecke/gas-check
Cloning into 'cgewecke/gas-check'...
$ cd cgewecke/gas-check
0.40s$ git fetch origin +refs/pull/21/merge:
From https://github.com/cgewecke/gas-check
 * branch            refs/pull/21/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

Example checkout for **Push**
```
$ git clone --depth=50 --branch=test-travis-2 https://github.com/cgewecke/gas-check.git cgewecke/gas-check
Cloning into 'cgewecke/gas-check'...
$ cd cgewecke/gas-check
$ git checkout -qf 35d62526f15a487392968f85ff23aeb81afa63d5
```

For pushes it's only cloning the commit branch and no other refs are available.

**Comment by krzkaczor** [comment]
@cgewecke thanks. I managed to get [debug builds](https://docs.travis-ci.com/user/running-build-in-debug-mode/) working and ssh directly to machine to play with various scenarios. This is what I realized.

There are 4 different flows (this is crazy):

1. New feature branch, no pr. 
Builds:
- `continuous-integration/travis-ci/pull`. This could use speculative branch feature BUT there is no need for it because...

2. New feature branch, pr created.
Builds:
- `continuous-integration/travis-ci/pull` from (1)
- `continuous-integration/travis-ci/pr` which is triggered by PRs. This is the best place to execute codechecks in PR mode. The only problem is that this branch is already merged with target branch so (`HEAD !== feature_branch !== base_branch`). This is slightly unintuitive for me but I guess it will be fine.

3. Base branch, commit. Builds:
- `continuous-integration/travis-ci/pull` basically (1)
This should execute codechecks but only record baselines.

4. Forked repo, PR. 
Builds:
- `continuous-integration/travis-ci/pr`
This should execute codechecks in fork mode (it's already implemented).

I took a look at your implementation and I think it's great. You were having problems with speculative execution but as shown above it's not really needed for TravisCI since we have separate builds when PR is created.

There needs to be additional property on `CiProvider` `supportsSpeculativeBranchSelection: boolean` which should be false for travis ci (but true for circleci). And there should be a check in `getExecutionContext` to skip speculative branches if this is false.

By doing this we should also be able to get rid of: https://github.com/cgewecke/gas-check/pull/21/files#diff-354f30a63fb0907d4ad57269548329e3R14 and then probably everything should work....

I know that this might sound complicated but I belive that this is fine implementation that will behave very similarly to what we have with CircleCI. I can work on it tmrw because I am probably very bad at explaining things @cgewecke ;) 

Side note, I found a nice way to get SHA of any branch: 

```sh
git fetch origin ANY_BRANCH && git rev-parse FETCH_HEAD
```

**Comment by cgewecke** [comment]
> git fetch origin ANY_BRANCH && git rev-parse FETCH_HEAD
Oh cool.

Everything you've said makes sense. I will check back here tomorrow then :)

**Comment by krzkaczor** [comment]
I created https://github.com/codechecks/monorepo/pull/12 branch with new commit disabling `speculative branch selection` for travis. It's deployed as `0.1.3-beta.0`. It seems to be working fine 🎉 https://github.com/krzkaczor/gas-check/pull/2 

Can u please give it a try as well? If you want to introduce any changes I think you can cherry-pick my commit to your fork and continue adding stuff. Otherwise, I would just close this PR and merge mine...

**Comment by krzkaczor** [comment]
Btw: I had some weird problems with installing `eth-gas-reporter` without npm lockfile. [Logs](https://travis-ci.org/krzkaczor/gas-check/builds/556488611?utm_source=github_status&utm_medium=notification)

Btw2: just tested forks: https://github.com/cgewecke/gas-check/pull/23 I think it works fine, there was just no base line recorded because build failed.

Btw3: I am not sure if I mentioned it to you but you can enable detailed logging with `DEBUG=codechecks:* yarn codechecks`


It looks like it works amazing! Generally, I hate travis CI but triggering builds on PR is not bad at all 🤔

**Comment by cgewecke** [comment]
> weird problems with installing eth-gas-reporter without npm lockfile

Ah. Thanks, that is weird. Probably web3. 

Your gas-check LGTM, super cool. Closing this in favor of #12.

**Pull request closed without merging**
