### PR TITLE
Added Github Actions as a provider

### PR DESCRIPTION
**Pull request by dericgw**
This addresses #47.

### CODE REVIEW

**Comment by krzkaczor** [comment]
Thanks so much for this, this is really great! ❤️ 

I hope you don't mind but it will take me a little bit (24h?) to properly review and merge this because I need to familiarize myself with GitHub Actions first. This becomes my #1 priority ;)

**Comment by dericgw** [comment]
Not at all! Take your time.

**Comment by krzkaczor** [comment]
Thanks @dericgw I merged it to tmp branch so I can conduct more tests before publishing it. I will let you know when it's done.

**Comment by krzkaczor** [comment]
@all-contributors please add @dericgw for code

**Pull request merged**
